import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ThemProvider } from "@/context/ThemContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemProvider className="px-24">
          <Navbar />
          <div className=" m-auto container flex  justify-center ">
            {children}
          </div>
          <Footer />
        </ThemProvider>
      </body>
    </html>
  );
}
